version: '3'

services:

  postgres:
    image: 'postgres:alpine'
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: transacao

  adminer:
    image: adminer
    ports:
      - 9000:8080